services:
  backend:
    image: node:lts-alpine3.19
    tty: true
    volumes:
      - type: bind
        source: "./src"
        target: "/app"
    working_dir: /app
    ports:
      - "3500:3000"
    command: "node server.mjs"
